
NODATA      = 0
BUILDINGS   = 1
NEW_BUILD   = 2
WALLS       = 11
PAVED       = 40
WATER       = 85
SOIL        = 125
LOW_VEG     = 170
DEDIC_TREES = 200
EVERG_TREES = 225
UNCLASS_VEG = 255


LEGEND = {
    NODATA: "NODATA",
    BUILDINGS: "BUILDINGS",
    WALLS: "WALLS",
    PAVED: "PAVED",
    WATER: "WATER",
    SOIL:  "SOIL",
    LOW_VEG: "LOW_VEG",
    DEDIC_TREES: "DEDIC_TREES",
    EVERG_TREES: "EVERG_TREES",
    UNCLASS_VEG: "UNCLASS_VEG"
}